"""
v1.12

PYTHON 3.12

pklib.bc - Python bytecode lib by PaketSoftware
MY GITHUB: https://github.com/PaketOs1nt
MY TELEGRAM: @paketls
MY TELEGRAM CHANNEL: @paketpksoftware

MIT LICENSE
"""

import dis
import importlib._bootstrap_external as imp_b
from types import CodeType
from typing import Iterator

map = {
    0: "CACHE",
    1: "POP_TOP",
    2: "PUSH_NULL",
    3: "INTERPRETER_EXIT",
    4: "END_FOR",
    5: "END_SEND",
    9: "NOP",
    11: "UNARY_NEGATIVE",
    12: "UNARY_NOT",
    15: "UNARY_INVERT",
    17: "RESERVED",
    25: "BINARY_SUBSCR",
    26: "BINARY_SLICE",
    27: "STORE_SLICE",
    30: "GET_LEN",
    31: "MATCH_MAPPING",
    32: "MATCH_SEQUENCE",
    33: "MATCH_KEYS",
    35: "PUSH_EXC_INFO",
    36: "CHECK_EXC_MATCH",
    37: "CHECK_EG_MATCH",
    49: "WITH_EXCEPT_START",
    50: "GET_AITER",
    51: "GET_ANEXT",
    52: "BEFORE_ASYNC_WITH",
    53: "BEFORE_WITH",
    54: "END_ASYNC_FOR",
    55: "CLEANUP_THROW",
    60: "STORE_SUBSCR",
    61: "DELETE_SUBSCR",
    68: "GET_ITER",
    69: "GET_YIELD_FROM_ITER",
    71: "LOAD_BUILD_CLASS",
    74: "LOAD_ASSERTION_ERROR",
    75: "RETURN_GENERATOR",
    83: "RETURN_VALUE",
    85: "SETUP_ANNOTATIONS",
    87: "LOAD_LOCALS",
    89: "POP_EXCEPT",
    90: "STORE_NAME",
    91: "DELETE_NAME",
    92: "UNPACK_SEQUENCE",
    93: "FOR_ITER",
    94: "UNPACK_EX",
    95: "STORE_ATTR",
    96: "DELETE_ATTR",
    97: "STORE_GLOBAL",
    98: "DELETE_GLOBAL",
    99: "SWAP",
    100: "LOAD_CONST",
    101: "LOAD_NAME",
    102: "BUILD_TUPLE",
    103: "BUILD_LIST",
    104: "BUILD_SET",
    105: "BUILD_MAP",
    106: "LOAD_ATTR",
    107: "COMPARE_OP",
    108: "IMPORT_NAME",
    109: "IMPORT_FROM",
    110: "JUMP_FORWARD",
    114: "POP_JUMP_IF_FALSE",
    115: "POP_JUMP_IF_TRUE",
    116: "LOAD_GLOBAL",
    117: "IS_OP",
    118: "CONTAINS_OP",
    119: "RERAISE",
    120: "COPY",
    121: "RETURN_CONST",
    122: "BINARY_OP",
    123: "SEND",
    124: "LOAD_FAST",
    125: "STORE_FAST",
    126: "DELETE_FAST",
    127: "LOAD_FAST_CHECK",
    128: "POP_JUMP_IF_NOT_NONE",
    129: "POP_JUMP_IF_NONE",
    130: "RAISE_VARARGS",
    131: "GET_AWAITABLE",
    132: "MAKE_FUNCTION",
    133: "BUILD_SLICE",
    134: "JUMP_BACKWARD_NO_INTERRUPT",
    135: "MAKE_CELL",
    136: "LOAD_CLOSURE",
    137: "LOAD_DEREF",
    138: "STORE_DEREF",
    139: "DELETE_DEREF",
    140: "JUMP_BACKWARD",
    141: "LOAD_SUPER_ATTR",
    142: "CALL_FUNCTION_EX",
    143: "LOAD_FAST_AND_CLEAR",
    144: "EXTENDED_ARG",
    145: "LIST_APPEND",
    146: "SET_ADD",
    147: "MAP_ADD",
    149: "COPY_FREE_VARS",
    150: "YIELD_VALUE",
    151: "RESUME",
    152: "MATCH_CLASS",
    155: "FORMAT_VALUE",
    156: "BUILD_CONST_KEY_MAP",
    157: "BUILD_STRING",
    162: "LIST_EXTEND",
    163: "SET_UPDATE",
    164: "DICT_MERGE",
    165: "DICT_UPDATE",
    171: "CALL",
    172: "KW_NAMES",
    173: "CALL_INTRINSIC_1",
    174: "CALL_INTRINSIC_2",
    175: "LOAD_FROM_DICT_OR_GLOBALS",
    176: "LOAD_FROM_DICT_OR_DEREF",
    237: "INSTRUMENTED_LOAD_SUPER_ATTR",
    238: "INSTRUMENTED_POP_JUMP_IF_NONE",
    239: "INSTRUMENTED_POP_JUMP_IF_NOT_NONE",
    240: "INSTRUMENTED_RESUME",
    241: "INSTRUMENTED_CALL",
    242: "INSTRUMENTED_RETURN_VALUE",
    243: "INSTRUMENTED_YIELD_VALUE",
    244: "INSTRUMENTED_CALL_FUNCTION_EX",
    245: "INSTRUMENTED_JUMP_FORWARD",
    246: "INSTRUMENTED_JUMP_BACKWARD",
    247: "INSTRUMENTED_RETURN_CONST",
    248: "INSTRUMENTED_FOR_ITER",
    249: "INSTRUMENTED_POP_JUMP_IF_FALSE",
    250: "INSTRUMENTED_POP_JUMP_IF_TRUE",
    251: "INSTRUMENTED_END_FOR",
    252: "INSTRUMENTED_END_SEND",
    253: "INSTRUMENTED_INSTRUCTION",
    254: "INSTRUMENTED_LINE",
    256: "SETUP_FINALLY",
    257: "SETUP_CLEANUP",
    258: "SETUP_WITH",
    259: "POP_BLOCK",
    260: "JUMP",
    261: "JUMP_NO_INTERRUPT",
    262: "LOAD_METHOD",
    263: "LOAD_SUPER_METHOD",
    264: "LOAD_ZERO_SUPER_METHOD",
    265: "LOAD_ZERO_SUPER_ATTR",
    266: "STORE_FAST_MAYBE_NULL",
}

CACHE = 0
POP_TOP = 1
PUSH_NULL = 2
INTERPRETER_EXIT = 3
END_FOR = 4
END_SEND = 5
NOP = 9
UNARY_NEGATIVE = 11
UNARY_NOT = 12
UNARY_INVERT = 15
RESERVED = 17
BINARY_SUBSCR = 25
BINARY_SLICE = 26
STORE_SLICE = 27
GET_LEN = 30
MATCH_MAPPING = 31
MATCH_SEQUENCE = 32
MATCH_KEYS = 33
PUSH_EXC_INFO = 35
CHECK_EXC_MATCH = 36
CHECK_EG_MATCH = 37
WITH_EXCEPT_START = 49
GET_AITER = 50
GET_ANEXT = 51
BEFORE_ASYNC_WITH = 52
BEFORE_WITH = 53
END_ASYNC_FOR = 54
CLEANUP_THROW = 55
STORE_SUBSCR = 60
DELETE_SUBSCR = 61
GET_ITER = 68
GET_YIELD_FROM_ITER = 69
LOAD_BUILD_CLASS = 71
LOAD_ASSERTION_ERROR = 74
RETURN_GENERATOR = 75
RETURN_VALUE = 83
SETUP_ANNOTATIONS = 85
LOAD_LOCALS = 87
POP_EXCEPT = 89
STORE_NAME = 90
DELETE_NAME = 91
UNPACK_SEQUENCE = 92
FOR_ITER = 93
UNPACK_EX = 94
STORE_ATTR = 95
DELETE_ATTR = 96
STORE_GLOBAL = 97
DELETE_GLOBAL = 98
SWAP = 99
LOAD_CONST = 100
LOAD_NAME = 101
BUILD_TUPLE = 102
BUILD_LIST = 103
BUILD_SET = 104
BUILD_MAP = 105
LOAD_ATTR = 106
COMPARE_OP = 107
IMPORT_NAME = 108
IMPORT_FROM = 109
JUMP_FORWARD = 110
POP_JUMP_IF_FALSE = 114
POP_JUMP_IF_TRUE = 115
LOAD_GLOBAL = 116
IS_OP = 117
CONTAINS_OP = 118
RERAISE = 119
COPY = 120
RETURN_CONST = 121
BINARY_OP = 122
SEND = 123
LOAD_FAST = 124
STORE_FAST = 125
DELETE_FAST = 126
LOAD_FAST_CHECK = 127
POP_JUMP_IF_NOT_NONE = 128
POP_JUMP_IF_NONE = 129
RAISE_VARARGS = 130
GET_AWAITABLE = 131
MAKE_FUNCTION = 132
BUILD_SLICE = 133
JUMP_BACKWARD_NO_INTERRUPT = 134
MAKE_CELL = 135
LOAD_CLOSURE = 136
LOAD_DEREF = 137
STORE_DEREF = 138
DELETE_DEREF = 139
JUMP_BACKWARD = 140
LOAD_SUPER_ATTR = 141
CALL_FUNCTION_EX = 142
LOAD_FAST_AND_CLEAR = 143
EXTENDED_ARG = 144
LIST_APPEND = 145
SET_ADD = 146
MAP_ADD = 147
COPY_FREE_VARS = 149
YIELD_VALUE = 150
RESUME = 151
MATCH_CLASS = 152
FORMAT_VALUE = 155
BUILD_CONST_KEY_MAP = 156
BUILD_STRING = 157
LIST_EXTEND = 162
SET_UPDATE = 163
DICT_MERGE = 164
DICT_UPDATE = 165
CALL = 171
KW_NAMES = 172
CALL_INTRINSIC_1 = 173
CALL_INTRINSIC_2 = 174
LOAD_FROM_DICT_OR_GLOBALS = 175
LOAD_FROM_DICT_OR_DEREF = 176
INSTRUMENTED_LOAD_SUPER_ATTR = 237
INSTRUMENTED_POP_JUMP_IF_NONE = 238
INSTRUMENTED_POP_JUMP_IF_NOT_NONE = 239
INSTRUMENTED_RESUME = 240
INSTRUMENTED_CALL = 241
INSTRUMENTED_RETURN_VALUE = 242
INSTRUMENTED_YIELD_VALUE = 243
INSTRUMENTED_CALL_FUNCTION_EX = 244
INSTRUMENTED_JUMP_FORWARD = 245
INSTRUMENTED_JUMP_BACKWARD = 246
INSTRUMENTED_RETURN_CONST = 247
INSTRUMENTED_FOR_ITER = 248
INSTRUMENTED_POP_JUMP_IF_FALSE = 249
INSTRUMENTED_POP_JUMP_IF_TRUE = 250
INSTRUMENTED_END_FOR = 251
INSTRUMENTED_END_SEND = 252
INSTRUMENTED_INSTRUCTION = 253
INSTRUMENTED_LINE = 254
SETUP_FINALLY = 256
SETUP_CLEANUP = 257
SETUP_WITH = 258
POP_BLOCK = 259
JUMP = 260
JUMP_NO_INTERRUPT = 261
LOAD_METHOD = 262
LOAD_SUPER_METHOD = 263
LOAD_ZERO_SUPER_METHOD = 264
LOAD_ZERO_SUPER_ATTR = 265
STORE_FAST_MAYBE_NULL = 266

BUILDERS_OP = (
    BUILD_LIST,
    BUILD_MAP,
    BUILD_SET,
    BUILD_TUPLE,
    BUILD_SLICE,
    BUILD_STRING,
    BUILD_CONST_KEY_MAP,
)
LOADERS_OP = (
    LOAD_GLOBAL,
    LOAD_NAME,
    LOAD_CONST,
    LOAD_FAST,
    LOAD_DEREF,
    LOAD_ATTR,
    LOAD_METHOD,
    LOAD_SUPER_ATTR,
    LOAD_SUPER_METHOD,
    LOAD_ZERO_SUPER_ATTR,
    LOAD_ZERO_SUPER_METHOD,
)
JUMP_OP = (
    JUMP,
    JUMP_BACKWARD,
    JUMP_BACKWARD_NO_INTERRUPT,
    JUMP_FORWARD,
    JUMP_NO_INTERRUPT,
    POP_JUMP_IF_FALSE,
    POP_JUMP_IF_NONE,
    POP_JUMP_IF_NOT_NONE,
    POP_JUMP_IF_TRUE,
)

type instr = tuple[str, int, int, int]  # 3.12 type style


def fast_calc_jump(self: instr) -> int:
    _, opcode, arg, pos = self
    if opcode in (JUMP_BACKWARD, JUMP_BACKWARD_NO_INTERRUPT):
        return pos - arg * 2

    if opcode == JUMP_FORWARD:
        return pos + arg * 2

    return arg * 2


def calc_jump(self: instr) -> int:
    op, opcode, arg, _ = self
    if opcode not in JUMP_OP:
        raise Exception(f"{op} is not JUMP_OP !")

    if not arg:
        raise Exception(f"{op} without arg :\\")

    return fast_calc_jump(self)


def op_name(i: int) -> str:
    return map.get(i, "<unknown-opcode>")


def fast_name(i: int) -> str:
    return map[i]


def unpack(code: bytes | bytearray, unpacker=fast_name) -> Iterator[instr]:
    for pos, op, arg in dis._unpack_opargs(code):  # type: ignore
        yield (unpacker(op), op, arg, pos)


def code_to_pyc(code: CodeType) -> bytes:
    return imp_b._code_to_timestamp_pyc(code)  # type: ignore
